#!/usr/bin/env bash
# shellcheck disable=SC2086
# Bash script that displays information about subdomains

allsubdomains=("www" "54.209.219.196" "18.235.233.59" "100.25.194.88")
prettifydig () {
    dig "$subdomain.$domain" | grep -A1 ';; ANSWER SECTION:' | grep -v 'ANSWER' | awk -v awksub="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", awksub, $4, $5}'
}

if [ $# -eq 1 ]
then 
    for a in "${allsubdomains[@]}"
    do
	domain="$1"
	subdomain="$a"
	prettifydig "$a" "$1"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    prettifydig "$2" "$1"
fi
