#!/usr/bin/env bash
#Transfer file to the server
if [ $# -lt 4 ];then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KE"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
