#!/usr/bin/env bash
# Write a Bash script that configures container to run nginx as nginx user, listen on all active IPs port 8080
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Store the username provided as an argument
USERNAME=$1

# Execute the whoami command as the specified user
echo "Running whoami as $USERNAME"
sudo -u $USERNAME whoami

sudo sed -i '4 i\user ${1};' /etc/nginx/nginx.conf
pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart

