#!/usr/bin/env bash

# Check if a username was provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Store the username provided as an argument
USERNAME=$1

# Fetch the home directory of the user
USER_HOME=$(getent passwd "$USERNAME" | cut -d: -f6)

# Execute the whoami command as the specified user
sudo -u "$USERNAME" whoami

# Print the home directory of the user
#echo "Home directory of "$USERNAME": "$USER_HOME""
